using System;
using System.Linq;
using Microsoft.Extensions.DependencyInjection;
using ZeroAlloc.Authorization;
using ZeroAlloc.Mediator;

namespace ZeroAlloc.Mediator.Authorization;

/// <summary>
/// Hooks the authorization pipeline into <see cref="IMediatorBuilder"/>. The configure
/// callback MUST select a security-context source — see <see cref="AuthorizationOptions"/>.
/// </summary>
public static class MediatorAuthorizationServiceCollectionExtensions
{
    public static IMediatorBuilder WithAuthorization(
        this IMediatorBuilder builder,
        Action<AuthorizationOptions>? configure = null)
    {
        ArgumentNullException.ThrowIfNull(builder);
        var services = builder.Services;
        var opts = new AuthorizationOptions(services);
        configure?.Invoke(opts);
        if (!opts.ContextSourceConfigured)
        {
            throw new InvalidOperationException(
                "WithAuthorization() requires a security-context source. Call ONE of: " +
                "UseSecurityContextFactory(sp => ...), UseAnonymousSecurityContext(), or " +
                "UseAccessor<TAccessor>() inside the configure callback.");
        }

        // D3 guard: ensure services.AddZeroAllocAuthorization() was called first. The bundled
        // generator in ZeroAlloc.Authorization v2 emits AddZeroAllocAuthorization(), which
        // registers your [Policy]-decorated classes plus the AuthorizerFor<TRequest> dispatchers
        // as scoped services. Without it, the behavior would silently fail-open on every request.
        var hasGeneratedRegistry = false;
        foreach (var sd in services)
        {
            if (sd.ServiceType.IsGenericType
                && sd.ServiceType.GetGenericTypeDefinition() == typeof(AuthorizerFor<>))
            {
                hasGeneratedRegistry = true;
                break;
            }
        }
        if (!hasGeneratedRegistry)
        {
            throw new InvalidOperationException(
                "WithAuthorization() requires services.AddZeroAllocAuthorization() to be called first. " +
                "Add 'services.AddZeroAllocAuthorization();' before 'services.AddMediator(...)' in Program.cs. " +
                "This call is generated by the ZeroAlloc.Authorization source generator and registers your " +
                "[Policy]-decorated classes plus the AuthorizerFor<TRequest> dispatchers as scoped services. " +
                "If you have no [Policy]/[RequirePolicy] usage yet, remove WithAuthorization() from your builder.");
        }

        // Idempotency guard: WithAuthorization may be called more than once safely.
        if (services.Any(d => d.ServiceType == typeof(AuthorizationBehaviorAccessor)))
            return builder;

        // Stash the IServiceProvider into the behavior's static state on first IServiceProvider
        // construction. Singleton service triggers state init once per provider build.
        services.AddSingleton(sp => new AuthorizationBehaviorAccessor(sp));

        return builder;
    }
}
