using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ZeroAlloc.Mediator.Authorization.Generator;

internal static class LookupEmitter
{
    public static string Emit(IReadOnlyList<PolicyModel> policies, IReadOnlyList<RequestModel> requests)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine("namespace ZeroAlloc.Mediator.Authorization");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class GeneratedAuthorizationLookup");
        sb.AppendLine("    {");
        sb.AppendLine("        private static readonly string[] EmptyPolicies = global::System.Array.Empty<string>();");
        sb.AppendLine();

        // GetPoliciesFor<TRequest>() — return string[] of policy names per request type, in declaration order.
        sb.AppendLine("        public static string[] GetPoliciesFor<TRequest>()");
        sb.AppendLine("        {");
        if (requests.Count == 0)
        {
            sb.AppendLine("            return EmptyPolicies;");
        }
        else
        {
            // Use sequential typeof-equality checks. typeof(TRequest) is JIT-resolved per closed
            // generic instantiation; the JIT folds the comparisons to a constant branch.
            sb.AppendLine("            var t = typeof(TRequest);");
            foreach (var req in requests)
            {
                var arr = string.Join(", ", req.PolicyNames.Select(EscapeStringLiteral));
                sb.AppendLine($"            if (t == typeof({req.FullyQualifiedTypeName})) return new string[] {{ {arr} }};");
            }
            sb.AppendLine("            return EmptyPolicies;");
        }
        sb.AppendLine("        }");
        sb.AppendLine();

        // GetPoliciesForType(Type) — non-generic mirror of GetPoliciesFor<T>, used by the
        // ModuleInitializer-installed hook. The JIT cannot fold this one to a constant branch
        // because the Type comes in via a runtime parameter, but it's still a tight switch
        // and is invoked once per request dispatch (same cost as the generic form once boxed).
        sb.AppendLine("        public static string[] GetPoliciesForType(global::System.Type t)");
        sb.AppendLine("        {");
        if (requests.Count == 0)
        {
            sb.AppendLine("            return EmptyPolicies;");
        }
        else
        {
            foreach (var req in requests)
            {
                var arr = string.Join(", ", req.PolicyNames.Select(EscapeStringLiteral));
                sb.AppendLine($"            if (t == typeof({req.FullyQualifiedTypeName})) return new string[] {{ {arr} }};");
            }
            sb.AppendLine("            return EmptyPolicies;");
        }
        sb.AppendLine("        }");
        sb.AppendLine();

        // Resolve(name, sp) — switch on name returning policy instance via sp.GetRequiredService<T>().
        // The cast to IAuthorizationPolicy is required at the IL level: GetRequiredService<TConcrete>()
        // returns TConcrete, not the interface. PolicyDiscovery filters out [AuthorizationPolicy]
        // types that don't implement IAuthorizationPolicy, so the cast is always safe.
        sb.AppendLine("        public static global::ZeroAlloc.Authorization.IAuthorizationPolicy Resolve(string name, global::System.IServiceProvider sp)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (name)");
        sb.AppendLine("            {");
        // Deduplicate by name (ZAMA002 fires on duplicates; emission picks first to keep code valid).
        var seen = new HashSet<string>(System.StringComparer.Ordinal);
        foreach (var p in policies)
        {
            if (!seen.Add(p.Name)) continue;
            sb.AppendLine($"                case {EscapeStringLiteral(p.Name)}: return (global::ZeroAlloc.Authorization.IAuthorizationPolicy)global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{p.FullyQualifiedTypeName}>(sp);");
        }
        sb.AppendLine("                default: throw new global::System.InvalidOperationException(\"Unknown policy '\" + name + \"'\");");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // PolicyTypes — Type[] for eager DI validation at startup.
        sb.AppendLine("        public static global::System.Type[] PolicyTypes { get; } = new global::System.Type[]");
        sb.AppendLine("        {");
        var seenTypes = new HashSet<string>(System.StringComparer.Ordinal);
        foreach (var p in policies)
        {
            if (!seenTypes.Add(p.FullyQualifiedTypeName)) continue;
            sb.AppendLine($"            typeof({p.FullyQualifiedTypeName}),");
        }
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string EmitDIExtensions(IReadOnlyList<PolicyModel> policies)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace ZeroAlloc.Mediator.Authorization");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class GeneratedAuthorizationDIExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        public static void RegisterDiscoveredPolicies(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("        {");
        var seen = new HashSet<string>(System.StringComparer.Ordinal);
        foreach (var p in policies)
        {
            if (!seen.Add(p.FullyQualifiedTypeName)) continue;
            sb.AppendLine($"            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<{p.FullyQualifiedTypeName}>(services);");
        }
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Emits a <c>[ModuleInitializer]</c> that wires the runtime's static delegate hooks
    /// to the generator-emitted lookup/DI methods. Without this, the runtime sub-package
    /// has no way to reach the user-compilation-local generated code.
    /// </summary>
    public static string EmitModuleInitializer(bool emitLookup, bool emitDI)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace ZeroAlloc.Mediator.Authorization");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class GeneratedAuthorizationModuleInitializer");
        sb.AppendLine("    {");
        sb.AppendLine("        [ModuleInitializer]");
        sb.AppendLine("        internal static void Init()");
        sb.AppendLine("        {");
        if (emitLookup)
        {
            sb.AppendLine("            global::ZeroAlloc.Mediator.Authorization.MediatorAuthorizationGeneratedHooks.GetPoliciesForRequestType =");
            sb.AppendLine("                global::ZeroAlloc.Mediator.Authorization.GeneratedAuthorizationLookup.GetPoliciesForType;");
            sb.AppendLine("            global::ZeroAlloc.Mediator.Authorization.MediatorAuthorizationGeneratedHooks.GetPolicyTypes =");
            sb.AppendLine("                static () => global::ZeroAlloc.Mediator.Authorization.GeneratedAuthorizationLookup.PolicyTypes;");
            sb.AppendLine("            global::ZeroAlloc.Mediator.Authorization.MediatorAuthorizationGeneratedHooks.ResolvePolicy =");
            sb.AppendLine("                global::ZeroAlloc.Mediator.Authorization.GeneratedAuthorizationLookup.Resolve;");
        }
        if (emitDI)
        {
            sb.AppendLine("            global::ZeroAlloc.Mediator.Authorization.MediatorAuthorizationGeneratedHooks.RegisterDiscoveredPolicies =");
            sb.AppendLine("                global::ZeroAlloc.Mediator.Authorization.GeneratedAuthorizationDIExtensions.RegisterDiscoveredPolicies;");
        }
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string EscapeStringLiteral(string s)
    {
        var escaped = s.Replace("\\", "\\\\").Replace("\"", "\\\"");
        return $"\"{escaped}\"";
    }
}
